version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: proyecto
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bigdata -d proyecto" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  spark-master:
    image: public.ecr.aws/bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark master (cluster)
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./scripts:/opt/bitnami/spark/scripts
    restart: unless-stopped

  spark-worker-1:
    image: public.ecr.aws/bitnami/spark:3.5
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/bitnami/spark/data
    restart: unless-stopped
volumes:
  pg_data: